version: '3.10'
services:
  employee-app:
    build:
      args:
        user: lucas
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    container_name: employee-app
    depends_on:
      - employee-app-db
    image: vexpenses-test-employee-app
    networks:
      - employee-app-net
    ports:
      - '8002:80'
    restart: unless-stopped
    volumes:
      - ./:/var/www/html/

  employee-app-db:
    image: mysql
    container_name: employee-app-db
    networks:
      - employee-app-net
    ports:
      - '33062:3306'
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

networks:
  employee-app-net:
    driver: bridge