version: '3.10'
services:
  employee-app:
    build:
      context: ./
      dockerfile: Dockerfile
    command: php artisan serve --host=0.0.0.0
    container_name: employee-app
    depends_on:
      - employee-app-db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: employee-app
    networks:
      - employee-app-net
    ports:
      - '8002:8000'
    volumes:
      - ./:/app

  employee-app-db:
    image: mysql
    container_name: employee-app-db
    networks:
      - employee-app-net
    ports:
      - '33062:3306'
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

  employee-app-cache:
    image: redis
    container_name: employee-app-cache
    networks:
      - employee-app-net
    ports:
      - '63792:6379'
    restart: unless-stopped

networks:
  employee-app-net:
    driver: bridge