version: '3.10'
services:
  company-app:
    build:
      context: ./
      dockerfile: Dockerfile
    command: php artisan serve --host=0.0.0.0
    container_name: company-app
    depends_on:
      - company-app-db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: company-app
    networks:
      - company-app-net
    ports:
      - '8003:8000'
    volumes:
      - ./:/app

  company-app-db:
    image: mysql
    container_name: company-app-db
    networks:
      - company-app-net
    ports:
      - '33063:3306'
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

networks:
  company-app-net:
    driver: bridge